# sh scripts/build_dev.sh && sh scripts/run_dev.sh

FROM node:latest AS development

# Declaring env
ENV NODE_ENV development

# Setting up the work directory
WORKDIR /app

# Installing dependencies
COPY ./package.json /app

# Starting our application
CMD npm run dev