import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TCC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt">
      {/* <body className={inter.className}>{children}</body> */}
      <body className="font-noto flex flex-col items-center justify-between w-3/4 max-w-3xl bg-gray-100">
        <div className="bg-white p-2 py-10">{children}</div>
      </body>
    </html>
  );
}
